// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Infrastructure.Persistence;

#nullable disable

namespace School.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251217124218_addDeviceTokenToStudentEnitiy1")]
    partial class addDeviceTokenToStudentEnitiy1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Class A",
                            TeacherName = "Mr. Ali"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Class B",
                            TeacherName = "Ms. Sara"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Class C",
                            TeacherName = "Mr. Hossam"
                        });
                });

            modelBuilder.Entity("School.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mathematics",
                            Name = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Arabic Language",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = 3,
                            Description = "History",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("School.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 2,
                            StudentId = 6
                        });
                });

            modelBuilder.Entity("School.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("School.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirebaseDeviceToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Email = "ahmed12@school.com",
                            Name = "Ahmed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 3,
                            Email = "khaled12@school.com",
                            Name = "Khaled",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 2,
                            Email = "eslam12@school.com",
                            Name = "Eslam",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            Email = "mariam12@school.com",
                            Name = "Mariam",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 3,
                            Email = "doaa12@school.com",
                            Name = "Doaa",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            Email = "zyad12@school.com",
                            Name = "Zeyad",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("School.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "12345",
                            RoleId = 3,
                            Username = "ahmed12"
                        },
                        new
                        {
                            Id = 2,
                            Password = "12345",
                            RoleId = 3,
                            Username = "khaled12"
                        },
                        new
                        {
                            Id = 3,
                            Password = "12345",
                            RoleId = 3,
                            Username = "eslam12"
                        },
                        new
                        {
                            Id = 4,
                            Password = "12345",
                            RoleId = 3,
                            Username = "mariam12"
                        },
                        new
                        {
                            Id = 5,
                            Password = "12345",
                            RoleId = 3,
                            Username = "doaa12"
                        },
                        new
                        {
                            Id = 6,
                            Password = "12345",
                            RoleId = 3,
                            Username = "zeyad12"
                        },
                        new
                        {
                            Id = 15,
                            Password = "12345",
                            RoleId = 1,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 16,
                            Password = "12345",
                            RoleId = 2,
                            Username = "Teacher"
                        });
                });

            modelBuilder.Entity("School.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("School.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School.Domain.Entities.Student", b =>
                {
                    b.HasOne("School.Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School.Domain.Entities.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("School.Domain.Entities.User", b =>
                {
                    b.HasOne("School.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("School.Domain.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("School.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("School.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("School.Domain.Entities.User", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
